# Connect to laminlabs/pertdata

This connects to the LaminDB perturbation instance and shows how to load a
curated AnnData object.

In [4]:
import lamindb as ln
import bionty as bt

→ connected lamindb: laminlabs/pertdata

In [2]:
ln.Artifact.filter().to_dataframe(limit=None)

,uid,key,description,suffix,kind,otype,size,hash,n_files,n_observations,version_tag,is_latest,is_locked,created_at,branch_id,space_id,storage_id,run_id,schema_id,created_by_id
id,,,,,,,,,,,,,,,,,,,,
671,GHqQn3Gldm2TDlKU0000,ginkgo-datapoints/vcpi/var.parquet,None,.parquet,dataset,DataFrame,876720,LzEXwVcKaMhH-Kwsf27CEA,NaN,59427.0,None,True,False,2026-02-14 01:52:04.633977+00:00,1,1,1,126.0,NaN,13
670,yVEHl7F0mKzyZkGN0000,ginkgo-datapoints/vcpi/X.h5ad,None,.h5ad,None,AnnData,1271058324,cZhr5vCHEcsDXDX__0rfyn,NaN,NaN,None,True,False,2026-02-14 01:50:28.092348+00:00,1,1,1,126.0,NaN,13
669,BE58T2T8yCNk026F0000,ginkgo-datapoints/vcpi/obs.parquet,None,.parquet,dataset,DataFrame,843718,ewj-ouMpoWVjNkiP6LLf1g,NaN,11808.0,None,True,False,2026-02-14 01:49:56.938511+00:00,1,1,1,126.0,37.0,13
666,Aks8cUD3SQFgILQP0000,DRUG-seq/GSE120222/var.parquet,None,.parquet,dataset,DataFrame,906771,RdwB3IyRh_40z3x0At1W9A,NaN,60371.0,None,True,False,2026-02-11 19:08:29.922376+00:00,1,1,1,125.0,NaN,13
665,E8CAkaQro1VVxzQH0000,DRUG-seq/GSE120222/X.h5ad,None,.h5ad,None,AnnData,40388452,rPK89WF4qsTgMMKyQqnOGA,NaN,NaN,None,True,False,2026-02-11 19:08:16.416886+00:00,1,1,1,125.0,NaN,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,e7Xv9gW1KQwOFYlE0000,scperturb/records/13350497/files/AdamsonWeissm...,None,.h5ad,None,AnnData,471286951,None,NaN,NaN,None,True,False,2025-01-10 15:02:46.199272+00:00,1,1,2,4.0,NaN,1
10,giLERJxsNL6XKBgR0000,scperturb/records/13350497/files/AdamsonWeissm...,None,.h5ad,None,AnnData,139059637,None,NaN,NaN,None,True,False,2025-01-10 15:02:40.359301+00:00,1,1,2,4.0,NaN,1
9,T1wl0JgqceOKPFyV0000,scperturb/records/13350497/files/AdamsonWeissm...,None,.h5ad,None,AnnData,34557246,None,NaN,NaN,None,True,False,2025-01-10 15:02:27.377925+00:00,1,1,2,4.0,NaN,1
6,rCNr6NMFJRo0cyzl0000,scperturb/mcfarland20/X.h5ad,None,.h5ad,dataset,AnnData,5737325239,UzcFYZnpPqRLmifY12YbRL,NaN,182875.0,None,True,False,2025-01-10 14:52:20.568603+00:00,1,1,1,3.0,NaN,1
3,ZFwrFuKM49fzIFLh0000,scperturb/records/13350497/files/McFarlandTshe...,None,.h5ad,None,AnnData,1459410830,None,NaN,NaN,None,True,False,2025-01-10 09:48:07.387493+00:00,1,1,2,2.0,NaN,1

In [1]:
# If needed, install packages (uncomment):
# %pip install lamindb bionty pertdata
# %lamin init --storage ./pertdata --modules bionty,pertdata
import lamindb as ln
import bionty as bt

db = ln.DB("laminlabs/pertdata")

→ connected lamindb: laminlabs/pertdata

In [ ]:
collection = db.Collection.filter(key="pertdata_datasets").one()

In [6]:
import sys
sys.path.append("../")
from tools.preprocess_collection import *

In [ ]:
schema = find_schema(db, schema_uid=None, schema_name=None)

NameError: name 'args' is not defined

In [1]:
import lamindb as ln

In [2]:
ln.setup.init(storage="gs://scperturb", modules="bionty,pertdata")

→ deleted instance record on hub 27b1bedd72315c6fb8826ea3d2cc8ffb

RuntimeError: Instance quota reached for this account.

In [ ]:
ln.Artifact.filter()

In [50]:
collection = ln.Collection(ln.Artifact.filter(), key="all")

! your collection contains artifacts with non-unique hashes:  ['0rpw5eQPw4lJJtQA0cm7EA', 'UippdXqhnbg78b34Ok7MNA', '0rpw5eQPw4lJJtQA0cm7EA']

NoWriteAccess: Unable to register a new user in the instance database because you have a read-only connection.

In [42]:
dataset_groups = group_collection_artifacts(collection, dataset_depth=1)

In [48]:
collection

Collection(uid='Q0Yf1Sx6ZUpmPSuL0000', version_tag=None, is_latest=True, key='pertdata_datasets', description='all relevant pertdata datasets as of 06.02.2025', hash='0FJ-Lg2TpNFHl8SPS5SIaQ', reference=None, reference_type=None, meta_artifact=None, branch_id=1, created_on_id=1, space_id=1, created_by_id=4, run_id=None, created_at=2025-02-06 14:23:11 UTC, is_locked=False)

In [11]:
arts = collection.artifacts.filter().to_dataframe(limit=None)

In [47]:
arts

,uid,key,description,suffix,kind,otype,size,hash,n_files,n_observations,...,is_latest,is_locked,created_at,branch_id,created_on_id,space_id,storage_id,run_id,schema_id,created_by_id
id,,,,,,,,,,,,,,,,,,,,,
172,jrky1vLP1jhlSkmK0000,scperturb/srivatsan20_sciplex2/X.h5ad,None,.h5ad,dataset,AnnData,490825170,gh5Xby3_fmWVUG-BYPgBSR,None,24262,...,True,False,2025-01-17 09:48:09.936929+00:00,1,1,1,1,51,None,1
171,Gp9iBKOXJfrfnaOd0000,scperturb/srivatsan20_sciplex4/X.h5ad,None,.h5ad,dataset,AnnData,849284895,t7Cpgd3nPw4vAOcjNgkTFK,None,98437,...,True,False,2025-01-17 09:31:31.000362+00:00,1,1,1,1,51,None,1
170,q66LZ79bsofePFX30000,scperturb/srivatsan20_sciplex3/X.h5ad,None,.h5ad,dataset,AnnData,12173078273,5sJ_PHlsxQ-M2uAwzb8syu,None,799317,...,True,False,2025-01-17 09:08:24.893536+00:00,1,1,1,1,85,None,1
157,y8RGOXIiMTZXRhUu0000,scperturb/papalexi21_eccite_RNA/X.h5ad,None,.h5ad,dataset,AnnData,516114972,hRSgzvQnxMDuyF-FqCiotD,None,20729,...,True,False,2025-01-15 13:32:03.310760+00:00,1,1,1,1,47,None,1
156,iovgATnS5iu1QkgW0000,scperturb/papalexi21_eccite_arrayed_RNA/X.h5ad,None,.h5ad,dataset,AnnData,171833488,7FFZcF--zJyMVZWxHTFw81,None,8984,...,True,False,2025-01-15 13:08:26.011864+00:00,1,1,1,1,47,None,1
149,VnSwS2axMroNzpxa0000,scperturb/zhao21/X.h5ad,None,.h5ad,dataset,AnnData,1928813984,lHbrssxlPfkips8teKGTZn,None,165748,...,True,False,2025-01-14 17:38:53.459829+00:00,1,1,1,1,45,None,1
145,Fo8n2HdweoS3KvJf0000,scperturb/xu23/X.h5ad,None,.h5ad,dataset,AnnData,2532897413,FqabvKgaJ6c97YILp5txyM,None,98315,...,True,False,2025-01-14 16:54:02.768865+00:00,1,1,1,1,43,None,1
140,WNTVSjbEvKLRqdJU0000,scperturb/wessels22/X.h5ad,None,.h5ad,dataset,AnnData,1107023858,M2es9CK2S1qUaie_i-2Qa5,None,30707,...,True,False,2025-01-14 16:27:02.564437+00:00,1,1,1,1,41,None,1
136,T0JXCgeLxtBwbDdb0000,scperturb/shifrut18/X.h5ad,None,.h5ad,dataset,AnnData,860364020,g5QH6Z-34OIQg3BoIJ4jf6,None,52236,...,True,False,2025-01-14 15:54:34.366630+00:00,1,1,1,1,38,None,1
131,G5MbzRwOd14iConk0000,scperturb/aissa21/X.h5ad,None,.h5ad,dataset,AnnData,149502079,GFn2L17_-WaQW4gttJzZzu,None,119071,...,True,False,2025-01-14 15:11:02.292739+00:00,1,1,1,1,37,None,1
127,E7pZHzRaxMWmefk80000,scperturb/adamson16_GSM2406675_10X001/X.h5ad,None,.h5ad,dataset,AnnData,122497964,aCwEF40-TBS1mNvQa5Vlj6,None,5768,...,True,False,2025-01-14 14:06:11.954542+00:00,1,1,1,1,12,None,1
123,pyJ7yapwpDvVlND90000,scperturb/replogle22_K562_gwps/X.h5ad,None,.h5ad,dataset,AnnData,75844637200,4A17fRw711a7ZtyfQ9Sd1i,None,1989578,...,True,False,2025-01-14 12:38:05.888608+00:00,1,1,1,1,8,None,1
122,cdTgT79SxGj3UJGy0000,scperturb/replogle22_K562_essential/X.h5ad,None,.h5ad,dataset,AnnData,9031133491,g902myOaoUCEuQNd7YKFsA,None,310385,...,True,False,2025-01-14 12:02:58.095783+00:00,1,1,1,1,8,None,1
121,4shJOZsjQveTwILa0000,scperturb/replogle22_RPE1/X.h5ad,None,.h5ad,dataset,AnnData,6985466190,TOcpEyfpUXlB08fxBpsLSk,None,247914,...,True,False,2025-01-14 11:52:10.356489+00:00,1,1,1,1,8,None,1
119,h1Xmuenf9GyCOQll0000,scperturb/adamson16_GSM2406681_10X010/X.h5ad,None,.h5ad,dataset,AnnData,1913997653,on2uwLLbAmDlfB4DpKTnln,None,65337,...,True,False,2025-01-14 09:20:58.726165+00:00,1,1,1,1,12,None,1
118,eWYpt9tMQVsFpoLG0000,scperturb/adamson16_GSM2406677_10X005/X.h5ad,None,.h5ad,dataset,AnnData,513723254,KuDuwvrwYdUv45It73z655,None,15006,...,True,False,2025-01-14 09:17:01.493413+00:00,1,1,1,1,12,None,1
115,rWKydySUypsQnfmI0000,scperturb/nadig24_jurkat/X.h5ad,None,.h5ad,dataset,AnnData,7394156316,mEfj0Mvi2bq4MsvqZvkcxG,None,262956,...,True,False,2025-01-14 08:51:30.385265+00:00,1,1,1,1,17,None,1
114,OyN0DCy2osWzNSab0000,scperturb/nadig24_hepg2/X.h5ad,None,.h5ad,dataset,AnnData,4859788511,3PghTBrRRZray1Sf6qVR96,None,145473,...,True,False,2025-01-14 08:47:59.731468+00:00,1,1,1,1,17,None,1
106,9dYsWA8ergJH8BkJ0000,scperturb/frangieh21/X.h5ad,None,.h5ad,dataset,AnnData,5765573186,XpVBoMqAkRe-qZFL4qKr89,None,218331,...,True,False,2025-01-13 16:15:10.736166+00:00,1,1,1,1,34,None,1
97,b6tQyIzsj1Sm1bv00000,scperturb/datlinger21/X.h5ad,None,.h5ad,dataset,AnnData,93319492,_otMM1S8821qpwJYAzeBvi,None,39194,...,True,False,2025-01-13 13:24:54.448808+00:00,1,1,1,1,31,None,1
94,AVlPOzYBdcrplGXk0000,scperturb/datlinger17/X.h5ad,None,.h5ad,dataset,AnnData,129576869,xZOVQ8LeticwYF_-a_Ije0,None,5905,...,True,False,2025-01-13 12:54:18.642625+00:00,1,1,1,1,30,None,1
91,zykqY3GIdwPPBN0i0000,scperturb/tian19_iPSC/X.h5ad,None,.h5ad,dataset,AnnData,1223494492,hp8UwNGAbWPye30Di1t2uu,None,275708,...,True,False,2025-01-13 11:32:13.821041+00:00,1,1,1,1,28,None,1
90,cm68xqb78HsBsagU0000,scperturb/tian19_day7neuron/X.h5ad,None,.h5ad,dataset,AnnData,928587678,pM-cphw6rMcyFGuip19Frt,None,182790,...,True,False,2025-01-13 11:23:54.112186+00:00,1,1,1,1,28,None,1
89,bLrtxPHlNJIsmBoe0000,scperturb/sunshine23/X.h5ad,None,.h5ad,dataset,AnnData,4105271808,54j-fbKZU44HVnZwAuJZd6,None,90380,...,True,False,2025-01-13 10:28:20.087978+00:00,1,1,1,1,23,None,1
84,eB7U5G9FAejglZRq0000,scperturb/dixit16_K562_TFs_High_MOI/X.h5ad,None,.h5ad,dataset,AnnData,1248346846,yvvTwAt35ZZzBp1YToiUv7,None,51898,...,True,False,2025-01-13 07:47:37.311553+00:00,1,1,1,1,20,None,1
83,1qlp8sGNsOba1tBo0000,scperturb/dixit16_K562_TFs_7_days/X.h5ad,None,.h5ad,dataset,AnnData,977287390,S-r_rOAW_DcakM0Nt7kHvb,None,33013,...,True,False,2025-01-13 07:08:27.286546+00:00,1,1,1,1,20,None,1
82,iV0xJ2VqkilWVt4p0000,scperturb/dixit16_K562_TFs_13_days/X.h5ad,None,.h5ad,dataset,AnnData,446282358,RNAWRthXGmJRrbYOw3Fl-M,None,19268,...,True,False,2025-01-13 07:02:48.655153+00:00,1,1,1,1,20,None,1
79,H1Qnzxdus1yPihMD0000,scperturb/norman19/X.h5ad,None,.h5ad,dataset,AnnData,2914146441,zI5VBJVzVx9zSFexa9efO3,None,111445,...,True,False,2025-01-13 06:21:18.835528+00:00,1,1,1,1,27,None,1
42,DOWRyPyiiBIF7BZj0000,scperturb/tian21_CRISPRa/X.h5ad,None,.h5ad,dataset,AnnData,596048020,E5WN8ghl_ua1o9FvaP1Yys,None,21193,...,True,False,2025-01-11 12:26:22.070192+00:00,1,1,1,1,14,None,1
41,vSuMxNZm0RZlrgo70000,scperturb/tian21_CRISPRi/X.h5ad,None,.h5ad,dataset,AnnData,1152946524,jAWPv0OIwWc0SzMHlVeM7N,None,32300,...,True,False,2025-01-11 12:20:59.137382+00:00,1,1,1,1,14,None,1
31,Ai0yn5OP1OECa9Rj0000,scperturb/chang22/X.h5ad,None,.h5ad,dataset,AnnData,1739492804,RAQDE6iLMHo1FVVkYiaZTK,None,42277,...,True,False,2025-01-11 09:56:21.251371+00:00,1,1,1,1,11,None,1
6,rCNr6NMFJRo0cyzl0000,scperturb/mcfarland20/X.h5ad,None,.h5ad,dataset,AnnData,5737325239,UzcFYZnpPqRLmifY12YbRL,None,182875,...,True,False,2025-01-10 14:52:20.568603+00:00,1,1,1,1,3,None,1

In [12]:
arts[arts.key.str.contains("adamson16_GSM2406675")]

,uid,key,description,suffix,kind,otype,size,hash,n_files,n_observations,...,is_latest,is_locked,created_at,branch_id,created_on_id,space_id,storage_id,run_id,schema_id,created_by_id
id,,,,,,,,,,,,,,,,,,,,,
127,E7pZHzRaxMWmefk80000,scperturb/adamson16_GSM2406675_10X001/X.h5ad,None,.h5ad,dataset,AnnData,122497964,aCwEF40-TBS1mNvQa5Vlj6,None,5768,...,True,False,2025-01-14 14:06:11.954542+00:00,1,1,1,1,12,None,1

In [46]:
dataset_groups[0]

DatasetGroup(dataset_key='scperturb', artifacts=[Artifact(uid='rCNr6NMFJRo0cyzl0000', version_tag=None, is_latest=True, key='scperturb/mcfarland20/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=5737325239, hash='UzcFYZnpPqRLmifY12YbRL', n_files=None, n_observations=182875, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=3, schema_id=None, created_by_id=1, created_at=2025-01-10 14:52:20 UTC, is_locked=False), Artifact(uid='Ai0yn5OP1OECa9Rj0000', version_tag=None, is_latest=True, key='scperturb/chang22/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=1739492804, hash='RAQDE6iLMHo1FVVkYiaZTK', n_files=None, n_observations=42277, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=11, schema_id=None, created_by_id=1, created_at=2025-01-11 09:56:21 UTC, is_locked=False), Artifact(uid='vSuMxNZm0RZlrgo70000', version_tag=None, is_latest=True, key='scperturb/tian21_CRISPRi/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=1152946524, hash='jAWPv0OIwWc0SzMHlVeM7N', n_files=None, n_observations=32300, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=14, schema_id=None, created_by_id=1, created_at=2025-01-11 12:20:59 UTC, is_locked=False), Artifact(uid='DOWRyPyiiBIF7BZj0000', version_tag=None, is_latest=True, key='scperturb/tian21_CRISPRa/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=596048020, hash='E5WN8ghl_ua1o9FvaP1Yys', n_files=None, n_observations=21193, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=14, schema_id=None, created_by_id=1, created_at=2025-01-11 12:26:22 UTC, is_locked=False), Artifact(uid='H1Qnzxdus1yPihMD0000', version_tag=None, is_latest=True, key='scperturb/norman19/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=2914146441, hash='zI5VBJVzVx9zSFexa9efO3', n_files=None, n_observations=111445, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=27, schema_id=None, created_by_id=1, created_at=2025-01-13 06:21:18 UTC, is_locked=False), Artifact(uid='iV0xJ2VqkilWVt4p0000', version_tag=None, is_latest=True, key='scperturb/dixit16_K562_TFs_13_days/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=446282358, hash='RNAWRthXGmJRrbYOw3Fl-M', n_files=None, n_observations=19268, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=20, schema_id=None, created_by_id=1, created_at=2025-01-13 07:02:48 UTC, is_locked=False), Artifact(uid='1qlp8sGNsOba1tBo0000', version_tag=None, is_latest=True, key='scperturb/dixit16_K562_TFs_7_days/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=977287390, hash='S-r_rOAW_DcakM0Nt7kHvb', n_files=None, n_observations=33013, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=20, schema_id=None, created_by_id=1, created_at=2025-01-13 07:08:27 UTC, is_locked=False), Artifact(uid='eB7U5G9FAejglZRq0000', version_tag=None, is_latest=True, key='scperturb/dixit16_K562_TFs_High_MOI/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=1248346846, hash='yvvTwAt35ZZzBp1YToiUv7', n_files=None, n_observations=51898, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=20, schema_id=None, created_by_id=1, created_at=2025-01-13 07:47:37 UTC, is_locked=False), Artifact(uid='bLrtxPHlNJIsmBoe0000', version_tag=None, is_latest=True, key='scperturb/sunshine23/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=4105271808, hash='54j-fbKZU44HVnZwAuJZd6', n_files=None, n_observations=90380, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=23, schema_id=None, created_by_id=1, created_at=2025-01-13 10:28:20 UTC, is_locked=False), Artifact(uid='cm68xqb78HsBsagU0000', version_tag=None, is_latest=True, key='scperturb/tian19_day7neuron/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=928587678, hash='pM-cphw6rMcyFGuip19Frt', n_files=None, n_observations=182790, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=28, schema_id=None, created_by_id=1, created_at=2025-01-13 11:23:54 UTC, is_locked=False), Artifact(uid='zykqY3GIdwPPBN0i0000', version_tag=None, is_latest=True, key='scperturb/tian19_iPSC/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=1223494492, hash='hp8UwNGAbWPye30Di1t2uu', n_files=None, n_observations=275708, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=28, schema_id=None, created_by_id=1, created_at=2025-01-13 11:32:13 UTC, is_locked=False), Artifact(uid='AVlPOzYBdcrplGXk0000', version_tag=None, is_latest=True, key='scperturb/datlinger17/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=129576869, hash='xZOVQ8LeticwYF_-a_Ije0', n_files=None, n_observations=5905, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=30, schema_id=None, created_by_id=1, created_at=2025-01-13 12:54:18 UTC, is_locked=False), Artifact(uid='b6tQyIzsj1Sm1bv00000', version_tag=None, is_latest=True, key='scperturb/datlinger21/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=93319492, hash='_otMM1S8821qpwJYAzeBvi', n_files=None, n_observations=39194, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=31, schema_id=None, created_by_id=1, created_at=2025-01-13 13:24:54 UTC, is_locked=False), Artifact(uid='9dYsWA8ergJH8BkJ0000', version_tag=None, is_latest=True, key='scperturb/frangieh21/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=5765573186, hash='XpVBoMqAkRe-qZFL4qKr89', n_files=None, n_observations=218331, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=34, schema_id=None, created_by_id=1, created_at=2025-01-13 16:15:10 UTC, is_locked=False), Artifact(uid='OyN0DCy2osWzNSab0000', version_tag=None, is_latest=True, key='scperturb/nadig24_hepg2/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=4859788511, hash='3PghTBrRRZray1Sf6qVR96', n_files=None, n_observations=145473, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=17, schema_id=None, created_by_id=1, created_at=2025-01-14 08:47:59 UTC, is_locked=False), Artifact(uid='rWKydySUypsQnfmI0000', version_tag=None, is_latest=True, key='scperturb/nadig24_jurkat/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=7394156316, hash='mEfj0Mvi2bq4MsvqZvkcxG', n_files=None, n_observations=262956, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=17, schema_id=None, created_by_id=1, created_at=2025-01-14 08:51:30 UTC, is_locked=False), Artifact(uid='eWYpt9tMQVsFpoLG0000', version_tag=None, is_latest=True, key='scperturb/adamson16_GSM2406677_10X005/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=513723254, hash='KuDuwvrwYdUv45It73z655', n_files=None, n_observations=15006, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=12, schema_id=None, created_by_id=1, created_at=2025-01-14 09:17:01 UTC, is_locked=False), Artifact(uid='h1Xmuenf9GyCOQll0000', version_tag=None, is_latest=True, key='scperturb/adamson16_GSM2406681_10X010/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=1913997653, hash='on2uwLLbAmDlfB4DpKTnln', n_files=None, n_observations=65337, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=12, schema_id=None, created_by_id=1, created_at=2025-01-14 09:20:58 UTC, is_locked=False), Artifact(uid='4shJOZsjQveTwILa0000', version_tag=None, is_latest=True, key='scperturb/replogle22_RPE1/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=6985466190, hash='TOcpEyfpUXlB08fxBpsLSk', n_files=None, n_observations=247914, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=8, schema_id=None, created_by_id=1, created_at=2025-01-14 11:52:10 UTC, is_locked=False), Artifact(uid='cdTgT79SxGj3UJGy0000', version_tag=None, is_latest=True, key='scperturb/replogle22_K562_essential/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=9031133491, hash='g902myOaoUCEuQNd7YKFsA', n_files=None, n_observations=310385, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=8, schema_id=None, created_by_id=1, created_at=2025-01-14 12:02:58 UTC, is_locked=False), Artifact(uid='pyJ7yapwpDvVlND90000', version_tag=None, is_latest=True, key='scperturb/replogle22_K562_gwps/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=75844637200, hash='4A17fRw711a7ZtyfQ9Sd1i', n_files=None, n_observations=1989578, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=8, schema_id=None, created_by_id=1, created_at=2025-01-14 12:38:05 UTC, is_locked=False), Artifact(uid='E7pZHzRaxMWmefk80000', version_tag=None, is_latest=True, key='scperturb/adamson16_GSM2406675_10X001/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=122497964, hash='aCwEF40-TBS1mNvQa5Vlj6', n_files=None, n_observations=5768, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=12, schema_id=None, created_by_id=1, created_at=2025-01-14 14:06:11 UTC, is_locked=False), Artifact(uid='G5MbzRwOd14iConk0000', version_tag=None, is_latest=True, key='scperturb/aissa21/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=149502079, hash='GFn2L17_-WaQW4gttJzZzu', n_files=None, n_observations=119071, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=37, schema_id=None, created_by_id=1, created_at=2025-01-14 15:11:02 UTC, is_locked=False), Artifact(uid='T0JXCgeLxtBwbDdb0000', version_tag=None, is_latest=True, key='scperturb/shifrut18/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=860364020, hash='g5QH6Z-34OIQg3BoIJ4jf6', n_files=None, n_observations=52236, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=38, schema_id=None, created_by_id=1, created_at=2025-01-14 15:54:34 UTC, is_locked=False), Artifact(uid='WNTVSjbEvKLRqdJU0000', version_tag=None, is_latest=True, key='scperturb/wessels22/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=1107023858, hash='M2es9CK2S1qUaie_i-2Qa5', n_files=None, n_observations=30707, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=41, schema_id=None, created_by_id=1, created_at=2025-01-14 16:27:02 UTC, is_locked=False), Artifact(uid='Fo8n2HdweoS3KvJf0000', version_tag=None, is_latest=True, key='scperturb/xu23/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=2532897413, hash='FqabvKgaJ6c97YILp5txyM', n_files=None, n_observations=98315, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=43, schema_id=None, created_by_id=1, created_at=2025-01-14 16:54:02 UTC, is_locked=False), Artifact(uid='VnSwS2axMroNzpxa0000', version_tag=None, is_latest=True, key='scperturb/zhao21/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=1928813984, hash='lHbrssxlPfkips8teKGTZn', n_files=None, n_observations=165748, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=45, schema_id=None, created_by_id=1, created_at=2025-01-14 17:38:53 UTC, is_locked=False), Artifact(uid='iovgATnS5iu1QkgW0000', version_tag=None, is_latest=True, key='scperturb/papalexi21_eccite_arrayed_RNA/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=171833488, hash='7FFZcF--zJyMVZWxHTFw81', n_files=None, n_observations=8984, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=47, schema_id=None, created_by_id=1, created_at=2025-01-15 13:08:26 UTC, is_locked=False), Artifact(uid='y8RGOXIiMTZXRhUu0000', version_tag=None, is_latest=True, key='scperturb/papalexi21_eccite_RNA/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=516114972, hash='hRSgzvQnxMDuyF-FqCiotD', n_files=None, n_observations=20729, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=47, schema_id=None, created_by_id=1, created_at=2025-01-15 13:32:03 UTC, is_locked=False), Artifact(uid='q66LZ79bsofePFX30000', version_tag=None, is_latest=True, key='scperturb/srivatsan20_sciplex3/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=12173078273, hash='5sJ_PHlsxQ-M2uAwzb8syu', n_files=None, n_observations=799317, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=85, schema_id=None, created_by_id=1, created_at=2025-01-17 09:08:24 UTC, is_locked=False), Artifact(uid='Gp9iBKOXJfrfnaOd0000', version_tag=None, is_latest=True, key='scperturb/srivatsan20_sciplex4/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=849284895, hash='t7Cpgd3nPw4vAOcjNgkTFK', n_files=None, n_observations=98437, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=51, schema_id=None, created_by_id=1, created_at=2025-01-17 09:31:31 UTC, is_locked=False), Artifact(uid='jrky1vLP1jhlSkmK0000', version_tag=None, is_latest=True, key='scperturb/srivatsan20_sciplex2/X.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=490825170, hash='gh5Xby3_fmWVUG-BYPgBSR', n_files=None, n_observations=24262, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=51, schema_id=None, created_by_id=1, created_at=2025-01-17 09:48:09 UTC, is_locked=False)])

In [ ]:
collection = db.Collection.get(key=args.collection_key)

In [36]:
db.Artifact.filter()[10]

Artifact(uid='vMOuOKi7uLWofyPg0000', version_tag=None, is_latest=True, key='scperturb/records/13350497/files/GasperiniShendure2019_atscale.h5ad', description=None, suffix='.h5ad', kind=None, otype='AnnData', size=1866293566, hash=None, n_files=None, n_observations=None, branch_id=1, created_on_id=1, space_id=1, storage_id=2, run_id=56, schema_id=None, created_by_id=1, created_at=2025-01-17 14:09:05 UTC, is_locked=False)

In [31]:
db.Schema.filter().to_dataframe()

,uid,name,description,n_members,coerce,flexible,itype,otype,hash,minimal_set,...,maximal_set,is_locked,is_type,created_at,branch_id,created_on_id,space_id,created_by_id,run_id,type_id
id,,,,,,,,,,,,,,,,,,,,,
79,z8SzcqomREdpG655,None,None,10,True,False,Feature,None,5IXEtOH3Q1ivZQuSXaUaKg,True,...,False,False,False,2026-02-18 21:08:10.456127+00:00,1,1,1,13,134,None
75,8JCEBZqmQ90lxOaQ,None,None,17,True,False,Feature,None,XsitJ3T3FVstK6-BPTsRVg,True,...,False,False,False,2025-12-17 14:17:04.304319+00:00,1,1,1,1,105,None
74,gExsggmnB1PU1aYV,None,None,16,True,False,Feature,None,mil_m-XB4V-YKKqyuve9KA,True,...,False,False,False,2025-12-17 13:56:55.422081+00:00,1,1,1,1,105,None
73,qoGz5ZPalwMVJdBB,None,None,16,True,False,Feature,None,luzPBnFacBBeLxEbHXD6rw,True,...,False,False,False,2025-12-17 13:29:58.832682+00:00,1,1,1,1,105,None
72,hCSBLGJuwZBcymIz,None,None,17,True,False,Feature,None,RODNqS45r4Vpfdb0dzqKoQ,True,...,False,False,False,2025-12-17 13:28:05.478154+00:00,1,1,1,1,105,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,K4Tu2tHoBi9kNph0,None,None,8563,None,False,bionty.Gene,None,-dnJg6lqRnM_P1S5YcfNlQ,True,...,False,False,False,2025-01-10 15:58:28.020359+00:00,1,1,1,1,8,None
4,m48qzpE9eZYBzfuy,None,None,14,None,False,Feature,None,mbdfpOaNmfNVpI4-C9mgOw,True,...,False,False,False,2025-01-10 15:44:38.954929+00:00,1,1,1,1,8,None
3,yYzdYvnC63IMEo8H,None,None,8749,None,False,bionty.Gene,None,BTNPPfMitD9OBijPQgQfmQ,True,...,False,False,False,2025-01-10 15:44:37.592183+00:00,1,1,1,1,8,None
2,VbZa5VRUG3ScbX6b,None,None,16,None,False,Feature,None,tEgX3drCUhxNzY3MBiL35g,True,...,False,False,False,2025-01-10 14:53:38.574864+00:00,1,1,1,1,3,None
1,Hsw90doQBx8Ci1QQ,None,None,32738,None,False,bionty.Gene,None,6iTVfBCwNVUc9KBr-BNuEQ,True,...,False,False,False,2025-01-10 14:53:33.760099+00:00,1,1,1,1,3,None

In [29]:
db.Feature.filter().to_dataframe(limit=None)

,uid,name,_dtype_str,unit,description,array_rank,array_size,array_shape,synonyms,default_value,...,coerce,is_locked,is_type,created_at,branch_id,created_on_id,space_id,created_by_id,run_id,type_id
id,,,,,,,,,,,,,,,,,,,,,
37,AWoc3HBYIOGn,pert_dose_multi,list[str],None,Multiple perturbation doses in form of a list....,0,0,None,None,None,...,False,False,False,2025-12-15 15:10:09.819486+00:00,1,1,1,1,105.0,None
36,qPIixNBCGu7b,pert_type_multi,list[cat[ULabel[380pmYI1]]],None,Multiple perturbation types in form of a list ...,0,0,None,None,None,...,False,False,False,2025-12-15 15:10:09.228531+00:00,1,1,1,1,105.0,None
35,3j8JE32meyTv,X,cat[Artifact],None,The corresponding adata.X artifact.,0,0,None,None,None,...,False,False,False,2025-11-18 14:05:42.338948+00:00,1,1,1,1,NaN,None
34,Pjr716yHHpCu,var,cat[Artifact],None,The corresponding adata.var artifact.,0,0,None,None,None,...,False,False,False,2025-11-14 15:48:56.065829+00:00,1,1,1,1,NaN,None
33,C2NXM8bQhk4j,obs,cat[Artifact],None,The corresponding adata.obs artifact.,0,0,None,None,None,...,False,False,False,2025-11-14 15:48:56.035787+00:00,1,1,1,1,NaN,None
31,MdAN9iTtQqcE,symbol,cat[bionty.Gene.symbol],None,Gene symbol.,0,0,None,None,None,...,False,False,False,2025-11-13 17:38:18.708321+00:00,1,1,1,1,87.0,None
30,AnJ88hMqhkba,ensembl_gene_id,cat[bionty.Gene.ensembl_gene_id],None,Ensembl gene identifier.,0,0,None,None,None,...,False,False,False,2025-11-13 17:38:18.672664+00:00,1,1,1,1,87.0,None
29,ozzfcSk9Fcyr,time,str,None,Timepoint of the experiment.,0,0,None,None,None,...,False,False,False,2025-11-13 12:48:01.342190+00:00,1,1,1,1,88.0,None
27,HkterUbGlJ5p,pert_biologic_multi,list[cat[pertdb.Biologic]],None,Biologic perturbations used for each perturbat...,0,0,None,pert_biologic,None,...,False,False,False,2025-07-29 13:02:04.050259+00:00,1,1,1,1,79.0,None
26,Gn0wvTbbi6qN,pert_compound_multi,list[cat[pertdb.Compound]],None,Compound perturbations for each perturbation i...,0,0,None,pert_compound,None,...,False,False,False,2025-07-29 13:02:03.857006+00:00,1,1,1,1,79.0,None
25,GiXWHqy6fZBQ,pert_genetic_multi,list[cat[pertdb.GeneticPerturbation]],None,Genetic perturbations for each perturbation in...,0,0,None,pert_genetic,None,...,False,False,False,2025-07-29 13:02:03.663247+00:00,1,1,1,1,79.0,None
24,2aw7tWKp58lT,pert_target_multi,list[cat[pertdb.PerturbationTarget]],None,Perturbation targets for each perturbation in ...,0,0,None,pert_target,None,...,False,False,False,2025-07-29 13:02:03.459258+00:00,1,1,1,1,79.0,None
23,bjBnO93fehI0,pert_type,cat[ULabel[380pmYI1]],None,"Required. 'genetic', 'compound', 'biologic', '...",0,0,None,None,None,...,False,False,False,2025-07-22 13:01:55.194379+00:00,1,1,1,1,68.0,None
22,IG4X0z2rR11g,pert_name,str,None,Required. The original name of the perturbatio...,0,0,None,None,None,...,False,False,False,2025-07-22 13:01:53.854890+00:00,1,1,1,1,68.0,None
21,z3DI4VKs3ri1,train_params,dict,None,None,0,0,None,None,None,...,False,False,False,2025-01-17 15:02:45.933408+00:00,1,1,1,4,NaN,None
20,gNW6qJwq3lmv,model_params,dict,None,None,0,0,None,None,None,...,False,False,False,2025-01-17 15:02:45.925029+00:00,1,1,1,4,NaN,None
19,dKMADIFRUkqd,pert_biologic,cat[pertdb.Biologic],None,Biologic perturbation. Used when 'pert_type' i...,0,0,None,None,None,...,False,False,False,2025-01-13 12:36:58.028868+00:00,1,1,1,1,30.0,None
17,RLiEYRHRIsnK,pert_target,cat[pertdb.PerturbationTarget],None,Target of the perturbation. Can be 'unknown'. ...,0,0,None,None,None,...,False,False,False,2025-01-10 15:40:32.587577+00:00,1,1,1,1,8.0,None
16,fz0lLSveCwiL,pert_time,str,None,Time of perturbation. In the form of float+uni...,0,0,None,None,None,...,False,False,False,2025-01-10 11:34:12.457800+00:00,1,1,1,1,3.0,None
15,TcFFHB8reYZt,pert_dose,str,None,Dose of the perturbagen. In the form of float+...,0,0,None,None,None,...,False,False,False,2025-01-10 11:34:12.087493+00:00,1,1,1,1,3.0,None
14,CKFmYmd8ze7w,pert_compound,cat[pertdb.Compound],None,Compound perturbation. Used when 'pert_type' i...,0,0,None,None,None,...,False,False,False,2025-01-10 11:33:30.119403+00:00,1,1,1,1,3.0,None
13,LlnhQlKmaOsc,pert_genetic,cat[pertdb.GeneticPerturbation],None,Genetic perturbation. Used when 'pert_type' is...,0,0,None,None,None,...,False,False,False,2025-01-10 11:33:30.119387+00:00,1,1,1,1,3.0,None
12,6uIWw21W477v,cell_line,cat[bionty.CellLine],None,Cell line used in the perturbation experiment.,0,0,None,None,None,...,False,False,False,2025-01-10 11:33:30.119371+00:00,1,1,1,1,3.0,None
11,SqEOZxNNGbvB,organism,cat[bionty.Organism],None,Required. The organism from which the sample w...,0,0,None,None,None,...,False,False,False,2025-01-10 11:33:30.119356+00:00,1,1,1,1,3.0,None
10,4B5RoEhcQHmj,tissue_type,cat[ULabel[FzEcREBL]],None,Required. 'tissue' or 'cell culture' or 'xenog...,0,0,None,None,None,...,False,False,False,2025-01-10 11:33:30.119339+00:00,1,1,1,1,3.0,None
9,iDQKCoXZuwlA,tissue,cat[bionty.Tissue],None,The tissue of samples used in the experiment.,0,0,None,None,None,...,False,False,False,2025-01-10 11:33:30.119322+00:00,1,1,1,1,3.0,None
8,Jo0fp8QbusNl,suspension_type,cat[ULabel[je7xSS9z]],None,Required. 'cell' or 'nucleus'.,0,0,None,None,None,...,False,False,False,2025-01-10 11:33:30.119306+00:00,1,1,1,1,3.0,None
7,N2nKqioRwW9m,sex,cat[bionty.Phenotype],None,Sex of the donor. 'male' or 'female' or 'unkno...,0,0,None,None,None,...,False,False,False,2025-01-10 11:33:30.119288+00:00,1,1,1,1,3.0,None
6,snOoyCaDgrdY,self_reported_ethnicity,cat[bionty.Ethnicity],None,Ethnicity of the donor. Can be 'unknown'.,0,0,None,None,None,...,False,False,False,2025-01-10 11:33:30.119271+00:00,1,1,1,1,3.0,None
5,6DXny2nLWdCZ,donor_id,str,None,"Donor identifier. If mixed, can be 'pooled'.",0,0,None,None,None,...,False,False,False,2025-01-10 11:33:30.119253+00:00,1,1,1,1,3.0,None
4,OiHfkw0r4Bml,disease,cat[bionty.Disease],None,"The disease of the sample donor, healthy is 'n...",0,0,None,None,None,...,False,False,False,2025-01-10 11:33:30.119233+00:00,1,1,1,1,3.0,None
3,HNJrKzUsn7Kd,development_stage,cat[bionty.DevelopmentalStage],None,Development stage of the biospecimen. Can be '...,0,0,None,None,None,...,False,False,False,2025-01-10 11:33:30.119214+00:00,1,1,1,1,3.0,None
2,dXBhcM2HNM2p,cell_type,cat[bionty.CellType],None,Cell type of the sample.,0,0,None,None,None,...,False,False,False,2025-01-10 11:33:30.119193+00:00,1,1,1,1,3.0,None
1,0rTLxGhs8Shs,assay,cat[bionty.ExperimentalFactor],None,Required. Assay used to measure the perturbati...,0,0,None,None,None,...,False,False,False,2025-01-10 11:33:30.119136+00:00,1,1,1,1,3.0,None

In [27]:
db.pertdb.Compound.filter().to_dataframe()

,uid,ontology_id,abbr,synonyms,description,name,type,chembl_id,smiles,canonical_smiles,...,molformula,moa,is_locked,created_at,branch_id,created_on_id,space_id,created_by_id,run_id,source_id
id,,,,,,,,,,,,,,,,,,,,,
233249,7lbz1SruwMGzHS,None,None,TTI-237 fumarate,None,Cevipabulin fumarate,None,None,None,None,...,None,None,False,2026-02-18 21:03:16.198299+00:00,1,1,1,13,134,NaN
233248,3y8ckErxixPjKx,None,None,Emetine 2HCl|NSC-33669,None,Emetine dihydrochloride hydrate,None,None,None,None,...,None,None,False,2026-02-18 21:03:11.208236+00:00,1,1,1,13,134,NaN
233247,3HoSSYu4s7dEd8,None,None,Dordaviprone|NSC350625|ONC201|TIC-10,None,TIC10 angular,None,None,None,None,...,None,None,False,2026-02-18 21:03:04.168290+00:00,1,1,1,13,134,NaN
233246,KprLElmDl3OOoT,None,None,Wytensin,None,Guanabenz acetate,None,None,None,None,...,None,None,False,2026-02-18 21:02:52.850742+00:00,1,1,1,13,134,NaN
233245,6qWXF36cjZGKAC,None,None,1-Methyl-4-phenylpyridinium|Cyperquat|MPP iodide,None,MPP+,None,None,None,None,...,None,None,False,2026-02-18 21:02:29.180024+00:00,1,1,1,13,134,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233024,1R5Mt8pDBzsHXc,None,None,None,None,unc-0646,None,None,None,COc1cc2c(NC3CCN(CC3)C3CCCCC3)nc(nc2cc1OCCCN1CC...,...,None,None,False,2025-09-29 17:52:30.470001+00:00,1,1,1,1,82,NaN
233023,rrx6yLg1e8aCZn,None,None,None,None,vu0155056,None,None,None,O=C(NCCN1CCC(CC1)n1c2ccccc2[nH]c1=O)c1ccc2cccc...,...,None,None,False,2025-09-29 17:52:30.470001+00:00,1,1,1,1,82,NaN
233022,6iZjFD9gwAPTYp,None,None,None,None,bms-906024,None,None,None,CN1c2ccccc2C(=N[C@H](NC(=O)[C@H](CCC(F)(F)F)[C...,...,None,None,False,2025-09-29 17:52:30.470001+00:00,1,1,1,1,82,NaN
233021,5ubJu1ffLOxn54,None,None,None,None,calpain inhibitor ii,None,None,None,CSCCC(NC(=O)C(CC(C)C)NC(=O)C(CC(C)C)NC(C)=O)C=O,...,None,None,False,2025-09-29 17:52:30.470001+00:00,1,1,1,1,82,NaN
233020,4bBaNY4tPgLMHV,None,None,None,None,epz-5676,None,None,None,CC(C)N(CC1OC(C(O)C1O)n2cnc3c(N)ncnc23)C4CC(CCc...,...,None,None,False,2025-09-29 17:52:30.470001+00:00,1,1,1,1,82,NaN

In [ ]:
ln.Features.filter().to_dataframe()

AttributeError: module 'lamindb' has no attribute 'Features'

In [22]:
import pertdb

pertdb.Compound.artifacts.rel

In [40]:
db.Artifact.filter().to_dataframe(limit=None)[db.Artifact.filter().to_dataframe(limit=None).key.str.split('/').str[1]=='2025-02-25']

,uid,key,description,suffix,kind,otype,size,hash,n_files,n_observations,...,is_latest,is_locked,created_at,branch_id,created_on_id,space_id,storage_id,run_id,schema_id,created_by_id
id,,,,,,,,,,,,,,,,,,,,,
246,cValvuqVvKDY5T8b0000,tahoe100m/2025-02-25/var.parquet,None,.parquet,dataset,DataFrame,1324368,f07nmZqAIFW6HUFxjNEvXA,NaN,62710.0,...,True,False,2025-07-23 18:14:21.512878+00:00,1,1,1,1,74.0,NaN,1
243,uOpawMuv6DnVIadP0000,tahoe100m/2025-02-25/plate14_filt_Vevo_Tahoe10...,Curated obs metadata for plate14,.parquet,dataset,DataFrame,221062501,OoGv4itI-8kXSdOkQxELwP,NaN,6518806.0,...,True,False,2025-07-23 15:37:44.967264+00:00,1,1,1,1,69.0,37.0,1
242,h8ML2WwxUgdT8Cn10000,tahoe100m/2025-02-25/plate13_filt_Vevo_Tahoe10...,Curated obs metadata for plate13,.parquet,dataset,DataFrame,290822142,0Rkkwhkm2cJmz9IrgK8-aC,NaN,8501658.0,...,True,False,2025-07-23 15:33:09.168727+00:00,1,1,1,1,69.0,37.0,1
241,sTKrKPpB5QpIV4iH0000,tahoe100m/2025-02-25/plate12_filt_Vevo_Tahoe10...,Curated obs metadata for plate12,.parquet,dataset,DataFrame,353120964,Ld7bu04sX_LzPp1OwLD_H6,NaN,10487057.0,...,True,False,2025-07-23 15:27:01.332911+00:00,1,1,1,1,69.0,37.0,1
240,sYsONFIQvd9Sh46U0000,tahoe100m/2025-02-25/plate11_filt_Vevo_Tahoe10...,Curated obs metadata for plate11,.parquet,dataset,DataFrame,248266928,g_V_jJ-LmzBwLpR6ZuO1eS,NaN,7435869.0,...,True,False,2025-07-23 15:20:43.017355+00:00,1,1,1,1,69.0,37.0,1
239,g8cnCPc2YwD9vfg60000,tahoe100m/2025-02-25/plate10_filt_Vevo_Tahoe10...,Curated obs metadata for plate10,.parquet,dataset,DataFrame,273754401,9pHavAy69ENT7tCxNMaoLr,NaN,8044908.0,...,True,False,2025-07-23 15:15:10.476688+00:00,1,1,1,1,69.0,37.0,1
238,PQSIhkmWMi38Ox620000,tahoe100m/2025-02-25/plate9_filt_Vevo_Tahoe100...,Curated obs metadata for plate9,.parquet,dataset,DataFrame,197518675,pEjeYLb-Tb54qOqfhp6J__,NaN,5866669.0,...,True,False,2025-07-23 15:07:50.408485+00:00,1,1,1,1,69.0,37.0,1
237,l0bOjTZKXiV8nmlH0000,tahoe100m/2025-02-25/plate8_filt_Vevo_Tahoe100...,Curated obs metadata for plate8,.parquet,dataset,DataFrame,303889166,SgRcAc8UKsb-TqYs7-QJbb,NaN,8880979.0,...,True,False,2025-07-23 15:03:23.922311+00:00,1,1,1,1,69.0,37.0,1
236,PUBDwkCFl6mdOTYr0000,tahoe100m/2025-02-25/plate7_filt_Vevo_Tahoe100...,Curated obs metadata for plate7,.parquet,dataset,DataFrame,190770986,8M1vnMaIoAmM9WL52tZq9U,NaN,5692117.0,...,True,False,2025-07-23 13:50:51.218020+00:00,1,1,1,1,69.0,37.0,1
235,IOuGOf4GPc9KVBgi0000,tahoe100m/2025-02-25/plate6_filt_Vevo_Tahoe100...,Curated obs metadata for plate6,.parquet,dataset,DataFrame,259733321,OqI0Pg1MRuyedHJB6crEBs,NaN,7545393.0,...,True,False,2025-07-23 13:43:45.291639+00:00,1,1,1,1,69.0,37.0,1
234,rQMqaImEQpXVJIwD0000,tahoe100m/2025-02-25/plate5_filt_Vevo_Tahoe100...,Curated obs metadata for plate5,.parquet,dataset,DataFrame,216015885,HX0ncmf69sdkW9AnbR844A,NaN,6419498.0,...,True,False,2025-07-23 13:38:43.232104+00:00,1,1,1,1,69.0,37.0,1
233,6SHCMwyJFbvNgvqI0000,tahoe100m/2025-02-25/plate4_filt_Vevo_Tahoe100...,Curated obs metadata for plate4,.parquet,dataset,DataFrame,234695583,ttbVGh9fNkP0lXnLrAlBHQ,NaN,7004356.0,...,True,False,2025-07-23 13:33:46.546828+00:00,1,1,1,1,69.0,37.0,1
232,o4c0PJ1lB02QwLBj0000,tahoe100m/2025-02-25/plate3_filt_Vevo_Tahoe100...,Curated obs metadata for plate3,.parquet,dataset,DataFrame,156216650,7ul2fY4euY2ifrSjVkR6Gt,NaN,4705402.0,...,True,False,2025-07-23 13:25:42.613389+00:00,1,1,1,1,69.0,37.0,1
231,TG9hJgIdaY8gKNe80000,tahoe100m/2025-02-25/plate2_filt_Vevo_Tahoe100...,Curated obs metadata for plate2,.parquet,dataset,DataFrame,272012731,YAdkM1yKR_r_F0QvjaZW5B,NaN,8064658.0,...,True,False,2025-07-23 13:21:53.981840+00:00,1,1,1,1,69.0,37.0,1
230,BkGlVEce52rFQS5l0000,tahoe100m/2025-02-25/plate1_filt_Vevo_Tahoe100...,Curated obs metadata for plate1,.parquet,dataset,DataFrame,183737105,j8wjq5Pl5VKFuNrrPgrXbS,NaN,5481420.0,...,True,False,2025-07-23 13:05:43.471170+00:00,1,1,1,1,69.0,37.0,1
220,BDttiuV3Te8VB0dU0000,tahoe100m/2025-02-25/plate9_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,18791302576,4kHbVbmreg6akW6ZgsjxaA,NaN,5866669.0,...,True,False,2025-02-25 23:22:22.759201+00:00,1,1,1,8,67.0,NaN,1
219,ZFeVfd0ugAHeWCxm0000,tahoe100m/2025-02-25/plate2_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,29037152127,usxviuqGbuw0RYnECCVCWw,NaN,8064658.0,...,True,False,2025-02-25 23:22:20.113956+00:00,1,1,1,8,67.0,NaN,1
218,omn7JStfJMzy8m6O0000,tahoe100m/2025-02-25/plate11_filt_Vevo_Tahoe10...,None,.h5ad,dataset,AnnData,23230802756,N2mzoYlMLEl6PdecaYyDvw,NaN,7435869.0,...,True,False,2025-02-25 23:22:18.229629+00:00,1,1,1,8,67.0,NaN,1
217,czC19UpUEszVH2bU0000,tahoe100m/2025-02-25/plate8_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,30390935958,ilAzEPIh4FlDeTFaJ1dILw,NaN,8880979.0,...,True,False,2025-02-25 23:22:22.387666+00:00,1,1,1,8,67.0,NaN,1
216,wadBkVuZ2yOOIrKa0000,tahoe100m/2025-02-25/metadata/sample_metadata....,None,.parquet,dataset,DataFrame,65636,vLYHp68bvPlKpXJusezDXA,NaN,1344.0,...,True,False,2025-02-25 19:33:43.178496+00:00,1,1,1,8,67.0,NaN,1
215,aJIqo7bNyJAs9z0r0000,tahoe100m/2025-02-25/plate1_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,19070623904,9iCNcouMqfNS3HA/2GUWOA,NaN,5481420.0,...,True,False,2025-02-25 23:22:19.737995+00:00,1,1,1,8,67.0,NaN,1
214,tKTeff0ugWqAm4P70000,tahoe100m/2025-02-25/plate4_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,23292672278,BkBXznbSovNWXtzPFITPcQ,NaN,7004356.0,...,True,False,2025-02-25 23:22:20.879928+00:00,1,1,1,8,67.0,NaN,1
213,aAHQ3zbD7n1asyYr0000,tahoe100m/2025-02-25/plate6_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,28934897078,NYvQEqVClziHm0ozWhOw1w,NaN,7545393.0,...,True,False,2025-02-25 23:22:21.629962+00:00,1,1,1,8,67.0,NaN,1
212,EZATJLC4jE7pmwo40000,tahoe100m/2025-02-25/plate5_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,19763140865,VMBKFzOI5cj7UC1UDENP4A,NaN,6419498.0,...,True,False,2025-02-25 23:22:21.255154+00:00,1,1,1,8,67.0,NaN,1
211,S2h2rPLCaUhZAM9u0000,tahoe100m/2025-02-25/plate12_filt_Vevo_Tahoe10...,None,.h5ad,dataset,AnnData,37495736876,VjAkWVFGVpzAMi9Innusuw,NaN,10487057.0,...,True,False,2025-02-25 23:22:18.600910+00:00,1,1,1,8,67.0,NaN,1
210,DC5cacdJr1VoEXnl0000,tahoe100m/2025-02-25/plate7_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,16514746341,NOS4MY6eYYPOnAB8ViyWYg,NaN,5692117.0,...,True,False,2025-02-25 23:22:22.009157+00:00,1,1,1,8,67.0,NaN,1
209,9L9HZ55HqUL0aqaR0000,tahoe100m/2025-02-25/plate13_filt_Vevo_Tahoe10...,None,.h5ad,dataset,AnnData,28071589885,RKOiaay+CHvv+Ukk/N+28A,NaN,8501658.0,...,True,False,2025-02-25 23:22:18.977981+00:00,1,1,1,8,67.0,NaN,1
208,vn5cUJCHbjpPPsZx0000,tahoe100m/2025-02-25/plate14_filt_Vevo_Tahoe10...,None,.h5ad,dataset,AnnData,22427932564,FrnStRehP16siRGG35ou+g,NaN,6518806.0,...,True,False,2025-02-25 23:22:19.357999+00:00,1,1,1,8,67.0,NaN,1
207,mUHMY4vxqnxMOclK0000,tahoe100m/2025-02-25/README.md,None,.md,None,None,368,aiKFGBEFe3VV6TLBIA3kyg,NaN,NaN,...,True,False,2025-02-25 19:31:29.489283+00:00,1,1,1,8,67.0,NaN,1
206,3Yl20zyG926CkvP50000,tahoe100m/2025-02-25/tutorial/plate3_2k-obs/X....,None,.h5ad,dataset,AnnData,7253540,vv16qryJsVY98jDBqhkr9w,NaN,2000.0,...,True,False,2025-02-25 19:31:01.255128+00:00,1,1,1,8,67.0,NaN,1
205,sxABPJYQPo3koqmN0000,tahoe100m/2025-02-25/metadata/obs_metadata_des...,None,.tsv,None,DataFrame,879,HBFLKDzsJzok7ONs0mRtEw,NaN,17.0,...,True,False,2025-02-25 19:33:42.909050+00:00,1,1,1,8,67.0,NaN,1
204,56uA9lPPmJ4zLUcr0000,tahoe100m/2025-02-25/plate10_filt_Vevo_Tahoe10...,None,.h5ad,dataset,AnnData,26536400717,j1FXsX7hs7u+eBqnWnmNHw,NaN,8044908.0,...,True,False,2025-02-25 23:22:17.849980+00:00,1,1,1,8,67.0,NaN,1
203,XVSrkq9pyF1OBLgG0000,tahoe100m/2025-02-25/plate3_filt_Vevo_Tahoe100...,None,.h5ad,dataset,AnnData,13173722269,Jnrt7DaSUCGn8D8LS2itaw,NaN,4705402.0,...,True,False,2025-02-25 23:22:20.497965+00:00,1,1,1,8,67.0,NaN,1
202,y1TTR9wbrmZEwpOa0000,tahoe100m/2025-02-25/metadata/obs_metadata.par...,None,.parquet,dataset,DataFrame,2293981573,qEWOpGw9CmQVzaElyMWT1Q,NaN,100648790.0,...,True,False,2025-02-25 19:33:42.721038+00:00,1,1,1,8,67.0,NaN,1

In [39]:
set(db.Artifact.filter().to_dataframe(limit=None).key.str.split('/').str[1])

{'2025-02-25',
 'GSE120222',
 'GSE305370',
 'GSE305979',
 'GSE306429',
 'GSE70138',
 'GSE92742',
 'Parse_10M_PBMC_cytokines.h5ad',
 'Parse_10M_PBMC_cytokines_curated.tiledbsoma',
 'Tahoe-100M-SCVI-v1',
 'adamson16_GSM2406675_10X001',
 'adamson16_GSM2406677_10X005',
 'adamson16_GSM2406681_10X010',
 'aissa21',
 'cell_line_metadata.parquet',
 'chang22',
 'datlinger17',
 'datlinger21',
 'dixit16_K562_TFs_13_days',
 'dixit16_K562_TFs_7_days',
 'dixit16_K562_TFs_High_MOI',
 'frangieh21',
 'geneinfo.parquet',
 'mcfarland20',
 'mock_model_scvi.pt',
 'model.pt',
 'nadig24_hepg2',
 'nadig24_jurkat',
 nan,
 'norman19',
 'papalexi21_eccite_RNA',
 'papalexi21_eccite_arrayed_RNA',
 'phase1',
 'phase2',
 'records',
 'replogle22_K562_essential',
 'replogle22_K562_gwps',
 'replogle22_RPE1',
 'shifrut18',
 'srivatsan20_sciplex2',
 'srivatsan20_sciplex3',
 'srivatsan20_sciplex4',
 'sunshine23',
 'tahoe100',
 'tian19_day7neuron',
 'tian19_iPSC',
 'tian21_CRISPRa',
 'tian21_CRISPRi',
 'vcpi',
 'wessels22',
 'xu23',
 'zhao21'}

In [ ]:
nadig24
aissa21
vcpi
replogle
dixit16
GSE1200
zhao21
xu23
wessels22
tian21
tian19
srivatsan20
mcfarland20

In [14]:
db.bionty.Organism.filter().to_dataframe(limit=None)

,uid,name,ontology_id,abbr,synonyms,description,scientific_name,is_locked,created_at,branch_id,space_id,created_by_id,run_id,source_id
id,,,,,,,,,,,,,,
2,3RZqbcSLWNGQGZ,mouse,NCBITaxon:10090,None,None,None,Mus musculus,False,2025-01-10 09:10:26.654102+00:00,1,1,1,1,1
1,1dpCL6TduFJ3AP,human,NCBITaxon:9606,None,None,None,Homo sapiens,False,2025-01-10 09:09:31.662158+00:00,1,1,1,1,1

In [12]:
db.bionty.Gene.filter().to_dataframe(limit=None)

,uid,abbr,synonyms,description,symbol,stable_id,ensembl_gene_id,ncbi_gene_ids,biotype,is_locked,created_at,branch_id,space_id,created_by_id,run_id,source_id,organism_id
id,,,,,,,,,,,,,,,,,
132480,4s1Zf4HuctP7KS,None,None,None,None,None,ENSG00000284737,None,None,False,2025-01-17 07:14:19.138328+00:00,1,1,1,51,NaN,1
132479,60sc1BU8AnSk4S,None,None,None,None,None,ENSG00000284714,None,None,False,2025-01-17 07:14:19.138328+00:00,1,1,1,51,NaN,1
132478,64l1gcpbVwxujl,None,None,None,None,None,ENSG00000284683,None,None,False,2025-01-17 07:14:19.138328+00:00,1,1,1,51,NaN,1
132477,6dmaRYJ3K9FA0J,None,None,None,None,None,ENSG00000284561,None,None,False,2025-01-17 07:14:19.138328+00:00,1,1,1,51,NaN,1
132476,5TKpJ4YHvun1Ye,None,None,None,None,None,ENSG00000284486,None,None,False,2025-01-17 07:14:19.138328+00:00,1,1,1,51,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,3wEqb6eOTZzC42,None,C1ORF112|FLJ10706|APOLO1|FLIP|MEICA1,FIGNL1 interacting regulator of recombination ...,FIRRM,None,ENSG00000000460,55732,protein_coding,False,2025-01-10 09:09:58.273264+00:00,1,1,1,1,11.0,1
4,5Zug63FETk4pJF,None,PACE1|PACE-1,SCY1 like pseudokinase 3,SCYL3,None,ENSG00000000457,57147,protein_coding,False,2025-01-10 09:09:58.273239+00:00,1,1,1,1,11.0,1
3,4eC1wUNJAO2s7T,None,CDGIE|MPDS,dolichyl-phosphate mannosyltransferase subunit...,DPM1,None,ENSG00000000419,8813,protein_coding,False,2025-01-10 09:09:58.273204+00:00,1,1,1,1,11.0,1
2,2FhduD7Z97Uvq1,None,TEM|MYODULIN|CHM1L|TENDIN|BRICD4,tenomodulin,TNMD,None,ENSG00000000005,64102,protein_coding,False,2025-01-10 09:09:58.273178+00:00,1,1,1,1,11.0,1
1,1uTi9dROoaN5rR,None,TSPAN-6|T245|TM4SF6,tetraspanin 6,TSPAN6,None,ENSG00000000003,7105,protein_coding,False,2025-01-10 09:09:58.273110+00:00,1,1,1,1,11.0,1